// SPDX-License-Identifier: UNLICENSED
// DO NOT edit this file. Code generated by forge-gen.
pragma solidity ^0.8.8;

import "../suavelib/Suave.sol";

library SuaveAddrs {
    function getSuaveAddrs() external pure returns (address[] memory) {
        address[] memory addrList = new address[](19);

        addrList[0] = Suave.IS_CONFIDENTIAL_ADDR;
        addrList[1] = Suave.BUILD_ETH_BLOCK;
        addrList[2] = Suave.CONFIDENTIAL_RETRIEVE;
        addrList[3] = Suave.CONFIDENTIAL_STORE;
        addrList[4] = Suave.CONTEXT_GET;
        addrList[5] = Suave.DO_HTTPREQUEST;
        addrList[6] = Suave.ETHCALL;
        addrList[7] = Suave.EXTRACT_HINT;
        addrList[8] = Suave.FETCH_DATA_RECORDS;
        addrList[9] = Suave.FILL_MEV_SHARE_BUNDLE;
        addrList[10] = Suave.NEW_BUILDER;
        addrList[11] = Suave.NEW_DATA_RECORD;
        addrList[12] = Suave.PRIVATE_KEY_GEN;
        addrList[13] = Suave.SIGN_ETH_TRANSACTION;
        addrList[14] = Suave.SIGN_MESSAGE;
        addrList[15] = Suave.SIMULATE_BUNDLE;
        addrList[16] = Suave.SIMULATE_TRANSACTION;
        addrList[17] = Suave.SUBMIT_BUNDLE_JSON_RPC;
        addrList[18] = Suave.SUBMIT_ETH_BLOCK_TO_RELAY;

        return addrList;
    }
}
